### PR TITLE
Use accelerated SHA-256 computatiion library

### PR DESCRIPTION
**Pull request by Wondertan**
This is a simple PR that swaps native SHA-256 calculation lib to [ASM accelerated one](https://github.com/minio/sha256-simd) that should give decent performance improvement.

### CODE REVIEW

**Comment by Wondertan** [comment]
If the proposal is ok, I will create further PRs in other repos that uses SHA-256

**Comment by adlerjohn** [comment]
This is sick!

**Comment by liamsi** [comment]
I think @musalbas did some benchmarks a few years ago. Similarly, there is this https://github.com/tendermint/tendermint/issues/2186

**Comment by Wondertan** [comment]
Closing as per sync discussion: we would like to keep `nmt` dependency-free, while a user can still use `sha256-simd` by providing custom hasher to `nmt`

**Pull request closed without merging**
